import { UpdateCustomJackupRig } from 'api/schema';
import { parseISO } from 'date-fns';
import { FormValues } from './useUpdateJackupForm';
import { normalizeDate, normalizeNumber } from 'utils/normalize';

export const normalizeValues = (
  values: FormValues,
  draft: boolean,
): Required<UpdateCustomJackupRig> => {
  return {
    name: values.name,
    manager: values.manager,
    design: values.design,
    build_yard: values.build_yard,
    rig_status: values.rig_status ?? '',
    design_score: values.design_score ?? '',
    topside_design: values.topside_design ?? '',
    end_of_last_contract: normalizeDate(values.end_of_last_contract),
    delivery_date: normalizeDate(values.delivery_date),
    special_survey_due: normalizeDate(values.special_survey_due),
    months_in_operation_last_year: normalizeNumber(
      values.months_in_operation_last_year,
    ),
    months_in_operation_last_3_years: normalizeNumber(
      values.months_in_operation_last_3_years,
    ),
    jack_down_time: normalizeNumber(values.jack_down_time),
    jack_up_time: normalizeNumber(values.jack_up_time),
    day_rate: normalizeNumber(values.day_rate),
    spread_cost: normalizeNumber(values.spread_cost),
    tugs_no_used: normalizeNumber(values.tugs_no_used),
    quarters_capacity: normalizeNumber(values.quarters_capacity),
    rig_water_depth: normalizeNumber(values.rig_water_depth),
    variable_load: normalizeNumber(values.variable_load),
    hull_breadth: normalizeNumber(values.hull_breadth),
    hull_depth: normalizeNumber(values.hull_depth),
    hull_length: normalizeNumber(values.hull_length),
    derrick_height: normalizeNumber(values.derrick_height),
    derrick_capacity: normalizeNumber(values.derrick_capacity),
    drawworks_power: normalizeNumber(values.drawworks_power),
    total_cranes: normalizeNumber(values.total_cranes),
    crane_capacity: normalizeNumber(values.crane_capacity),
    total_bop_rams: normalizeNumber(values.total_bop_rams),
    bop_diameter_wp_max: normalizeNumber(values.bop_diameter_wp_max),
    bop_wp_max: normalizeNumber(values.bop_wp_max),
    number_of_bop_stacks: normalizeNumber(values.number_of_bop_stacks),
    mudpump_quantity: normalizeNumber(values.mudpump_quantity),
    liquid_mud: normalizeNumber(values.liquid_mud),
    mud_total_power: normalizeNumber(values.mud_total_power),
    shaleshaker_total: normalizeNumber(values.shaleshaker_total),
    engine_power: normalizeNumber(values.engine_power),
    engine_quantity: normalizeNumber(values.engine_quantity),
    engine_total: normalizeNumber(values.engine_total),
    generator_power: normalizeNumber(values.generator_power),
    generator_quantity: normalizeNumber(values.generator_quantity),
    generator_total: normalizeNumber(values.generator_total),
    cantilever_reach: normalizeNumber(values.cantilever_reach),
    cantilever_lateral: normalizeNumber(values.cantilever_lateral),
    cantilever_capacity: normalizeNumber(values.cantilever_capacity),
    leg_length: normalizeNumber(values.leg_length),
    leg_spacing: normalizeNumber(values.leg_spacing),
    offline_stand_building: values.offline_stand_building ?? false,
    auto_pipe_handling: values.auto_pipe_handling ?? false,
    dual_activity: values.dual_activity ?? false,
    drilltronic: values.drilltronic ?? false,
    subsea_drilling: values.subsea_drilling ?? false,
    enhanced_legs: values.enhanced_legs ?? false,
    dynamic_drilling_guide: values.dynamic_drilling_guide ?? false,
    process_automation_platform: values.process_automation_platform ?? false,
    automatic_tripping: values.automatic_tripping ?? false,
    closed_bus: values.closed_bus ?? false,
    scr: values.scr ?? false,
    hybrid: values.hybrid ?? false,
    hvac_heat_recovery: values.hvac_heat_recovery ?? false,
    freshwater_cooling_systems: values.freshwater_cooling_systems ?? false,
    seawater_cooling_systems: values.seawater_cooling_systems ?? false,
    operator_awareness_dashboard: values.operator_awareness_dashboard ?? false,
    hpu_optimization: values.hpu_optimization ?? false,
    optimized_heat_tracing_system:
      values.optimized_heat_tracing_system ?? false,
    floodlighting_optimization: values.floodlighting_optimization ?? false,
    vfds_on_aux_machinery: values.vfds_on_aux_machinery ?? false,
    draft,
  };
};

export const getInitialValues = (
  jackupRigData: UpdateCustomJackupRig,
): FormValues => {
  return {
    name: jackupRigData.name ?? '',
    manager: jackupRigData.manager ?? '',
    design: jackupRigData.design ?? '',
    build_yard: jackupRigData.build_yard ?? '',
    rig_status: jackupRigData.rig_status || null,
    delivery_date: jackupRigData.delivery_date
      ? parseISO(jackupRigData.delivery_date)
      : null,
    special_survey_due: jackupRigData.special_survey_due
      ? parseISO(jackupRigData.special_survey_due)
      : null,
    end_of_last_contract: jackupRigData.end_of_last_contract
      ? parseISO(jackupRigData.end_of_last_contract)
      : null,
    months_in_operation_last_year:
      jackupRigData.months_in_operation_last_year ?? '',
    months_in_operation_last_3_years:
      jackupRigData.months_in_operation_last_3_years ?? '',
    design_score: jackupRigData.design_score || null,
    topside_design: jackupRigData.topside_design || null,
    tugs_no_used: jackupRigData.tugs_no_used ?? '',
    jack_down_time: jackupRigData.jack_down_time ?? '',
    jack_up_time: jackupRigData.jack_up_time ?? '',
    day_rate: jackupRigData.day_rate ?? '',
    spread_cost: jackupRigData.spread_cost ?? '',
    quarters_capacity: jackupRigData.quarters_capacity ?? '',
    rig_water_depth: jackupRigData.rig_water_depth ?? '',
    variable_load: jackupRigData.variable_load ?? '',
    hull_breadth: jackupRigData.hull_breadth ?? '',
    hull_depth: jackupRigData.hull_depth ?? '',
    hull_length: jackupRigData.hull_length ?? '',
    derrick_height: jackupRigData.derrick_height ?? '',
    derrick_capacity: jackupRigData.derrick_capacity ?? '',
    drawworks_power: jackupRigData.drawworks_power ?? '',
    total_cranes: jackupRigData.total_cranes ?? '',
    crane_capacity: jackupRigData.crane_capacity ?? '',
    total_bop_rams: jackupRigData.total_bop_rams ?? '',
    bop_diameter_wp_max: jackupRigData.bop_diameter_wp_max ?? '',
    bop_wp_max: jackupRigData.bop_wp_max ?? '',
    number_of_bop_stacks: jackupRigData.number_of_bop_stacks ?? '',
    mudpump_quantity: jackupRigData.mudpump_quantity ?? '',
    liquid_mud: jackupRigData.liquid_mud ?? '',
    mud_total_power: jackupRigData.mud_total_power ?? '',
    shaleshaker_total: jackupRigData.shaleshaker_total ?? '',
    engine_power: jackupRigData.engine_power ?? '',
    engine_quantity: jackupRigData.engine_quantity ?? '',
    engine_total: jackupRigData.engine_total ?? '',
    generator_power: jackupRigData.generator_power ?? '',
    generator_quantity: jackupRigData.generator_quantity ?? '',
    generator_total: jackupRigData.generator_total ?? '',
    cantilever_reach: jackupRigData.cantilever_reach ?? '',
    cantilever_lateral: jackupRigData.cantilever_lateral ?? '',
    cantilever_capacity: jackupRigData.cantilever_capacity ?? '',
    leg_length: jackupRigData.leg_length ?? '',
    leg_spacing: jackupRigData.leg_spacing ?? '',
    offline_stand_building: jackupRigData.offline_stand_building ?? false,
    auto_pipe_handling: jackupRigData.auto_pipe_handling ?? false,
    dual_activity: jackupRigData.dual_activity ?? false,
    drilltronic: jackupRigData.drilltronic ?? false,
    subsea_drilling: jackupRigData.subsea_drilling ?? false,
    enhanced_legs: jackupRigData.enhanced_legs ?? false,
    dynamic_drilling_guide: jackupRigData.dynamic_drilling_guide ?? false,
    process_automation_platform:
      jackupRigData.process_automation_platform ?? false,
    automatic_tripping: jackupRigData.automatic_tripping ?? false,
    closed_bus: jackupRigData.closed_bus ?? false,
    scr: jackupRigData.scr ?? false,
    hybrid: jackupRigData.hybrid ?? false,
    hvac_heat_recovery: jackupRigData.hvac_heat_recovery ?? false,
    freshwater_cooling_systems:
      jackupRigData.freshwater_cooling_systems ?? false,
    seawater_cooling_systems: jackupRigData.seawater_cooling_systems ?? false,
    operator_awareness_dashboard:
      jackupRigData.operator_awareness_dashboard ?? false,
    hpu_optimization: jackupRigData.hpu_optimization ?? false,
    optimized_heat_tracing_system:
      jackupRigData.optimized_heat_tracing_system ?? false,
    floodlighting_optimization:
      jackupRigData.floodlighting_optimization ?? false,
    vfds_on_aux_machinery: jackupRigData.vfds_on_aux_machinery ?? false,
  };
};

export const emptyValues: FormValues = {
  name: '',
  manager: '',
  design: '',
  build_yard: '',
  rig_status: null,
  delivery_date: null,
  special_survey_due: null,
  end_of_last_contract: null,
  months_in_operation_last_year: '',
  months_in_operation_last_3_years: '',
  design_score: null,
  topside_design: null,
  quarters_capacity: '',
  spread_cost: '',
  day_rate: '',
  jack_up_time: '',
  jack_down_time: '',
  tugs_no_used: '',
  rig_water_depth: '',
  variable_load: '',
  hull_breadth: '',
  hull_depth: '',
  hull_length: '',
  derrick_height: '',
  derrick_capacity: '',
  drawworks_power: '',
  total_cranes: '',
  crane_capacity: '',
  total_bop_rams: '',
  bop_diameter_wp_max: '',
  bop_wp_max: '',
  number_of_bop_stacks: '',
  mudpump_quantity: '',
  liquid_mud: '',
  mud_total_power: '',
  shaleshaker_total: '',
  engine_power: '',
  engine_quantity: '',
  engine_total: '',
  generator_power: '',
  generator_quantity: '',
  generator_total: '',
  cantilever_reach: '',
  cantilever_lateral: '',
  cantilever_capacity: '',
  leg_length: '',
  leg_spacing: '',
  offline_stand_building: false,
  auto_pipe_handling: false,
  dual_activity: false,
  drilltronic: false,
  subsea_drilling: false,
  enhanced_legs: false,
  dynamic_drilling_guide: false,
  process_automation_platform: false,
  automatic_tripping: false,
  closed_bus: false,
  scr: false,
  hybrid: false,
  hvac_heat_recovery: false,
  freshwater_cooling_systems: false,
  seawater_cooling_systems: false,
  operator_awareness_dashboard: false,
  hpu_optimization: false,
  optimized_heat_tracing_system: false,
  floodlighting_optimization: false,
  vfds_on_aux_machinery: false,
};
