import { FormValues } from './form';
import {
  CustomDrillshipDetails,
  DpClassEnum,
  DrillfloorEfficiencyEnum,
  RigStatusEnum,
  TopsideDesignEnum,
  UpdateCustomDrillship,
} from 'api/schema';
import { normalizeDate, normalizeNumber } from 'utils/normalize';
import { parseISO } from 'date-fns';

export const normalizeFormValues = (
  values: FormValues,
  draft: boolean,
): Required<UpdateCustomDrillship> => {
  return {
    name: values.name,
    manager: values.manager,
    design: values.design,
    build_yard: values.build_yard,
    rig_status: values.rig_status ?? '',
    delivery_date: normalizeDate(values.delivery_date),
    special_survey_due: normalizeDate(values.special_survey_due),
    end_of_last_contract: normalizeDate(values.end_of_last_contract),
    months_in_operation_last_year: normalizeNumber(
      values.months_in_operation_last_year,
    ),
    months_in_operation_last_3_years: normalizeNumber(
      values.months_in_operation_last_3_years,
    ),
    design_score: values.design_score ?? '',
    equipment_load: values.equipment_load ?? '',
    topside_design: values.topside_design ?? '',
    day_rate: normalizeNumber(values.day_rate),
    spread_cost: normalizeNumber(values.spread_cost),
    tugs_no_used: normalizeNumber(values.tugs_no_used),
    drillfloor_efficiency: values.drillfloor_efficiency ?? '',
    quarters_capacity: normalizeNumber(values.quarters_capacity),
    rig_water_depth: normalizeNumber(values.rig_water_depth),
    variable_load: normalizeNumber(values.variable_load),
    hull_concept_score: normalizeNumber(values.hull_concept_score),
    hull_design_eco_score: normalizeNumber(values.hull_design_eco_score),
    dp: values.dp,
    dp_class: values.dp_class ?? '',
    draft_depth: normalizeNumber(values.draft_depth),
    displacement: normalizeNumber(values.displacement),
    hull_breadth: normalizeNumber(values.hull_breadth),
    hull_depth: normalizeNumber(values.hull_depth),
    hull_length: normalizeNumber(values.hull_length),
    derrick_height: normalizeNumber(values.derrick_height),
    derrick_capacity: normalizeNumber(values.derrick_capacity),
    dual_derrick: values.dual_derrick,
    drawworks_power: normalizeNumber(values.drawworks_power),
    active_heave_drawwork: values.active_heave_drawwork,
    cmc_with_active_heave: values.cmc_with_active_heave,
    ram_system: values.ram_system,
    total_cranes: normalizeNumber(values.total_cranes),
    crane_capacity: normalizeNumber(values.crane_capacity),
    riser_on_board_outfitted: normalizeNumber(values.riser_on_board_outfitted),
    riser_storage_inside_hull: values.riser_storage_inside_hull,
    split_funnels_free_stern_deck: values.split_funnels_free_stern_deck,
    total_bop_rams: normalizeNumber(values.total_bop_rams),
    bop_diameter_wp_max: normalizeNumber(values.bop_diameter_wp_max),
    bop_wp_max: normalizeNumber(values.bop_wp_max),
    number_of_bop_stacks: normalizeNumber(values.number_of_bop_stacks),
    mudpump_quantity: normalizeNumber(values.mudpump_quantity),
    liquid_mud: normalizeNumber(values.liquid_mud),
    mud_total_power: normalizeNumber(values.mud_total_power),
    shaleshaker_total: normalizeNumber(values.shaleshaker_total),
    engine_power: normalizeNumber(values.engine_power),
    engine_quantity: normalizeNumber(values.engine_quantity),
    engine_total: normalizeNumber(values.engine_total),
    generator_power: normalizeNumber(values.generator_power),
    generator_quantity: normalizeNumber(values.generator_quantity),
    generator_total: normalizeNumber(values.generator_total),
    tripsaver: values.tripsaver,
    offline_stand_building: values.offline_stand_building,
    auto_pipe_handling: values.auto_pipe_handling,
    dual_activity: values.dual_activity,
    drilltronic: values.drilltronic,
    dynamic_drilling_guide: values.dynamic_drilling_guide,
    process_automation_platform: values.process_automation_platform,
    automatic_tripping: values.automatic_tripping,
    closed_bus: values.closed_bus,
    scr: values.scr,
    hybrid: values.hybrid,
    hvac_heat_recovery: values.hvac_heat_recovery,
    freshwater_cooling_systems: values.freshwater_cooling_systems,
    seawater_cooling_systems: values.seawater_cooling_systems,
    operator_awareness_dashboard: values.operator_awareness_dashboard,
    hpu_optimization: values.hpu_optimization,
    optimized_heat_tracing_system: values.optimized_heat_tracing_system,
    floodlighting_optimization: values.floodlighting_optimization,
    vfds_on_aux_machinery: values.vfds_on_aux_machinery,
    draft,
  };
};

export const getInitialFormValues = (
  rigData: CustomDrillshipDetails,
): FormValues => {
  return {
    name: rigData.name ?? '',
    manager: rigData.manager ?? '',
    design: rigData.design ?? '',
    build_yard: rigData.build_yard ?? '',
    rig_status: rigData.rig_status
      ? (rigData.rig_status as RigStatusEnum)
      : null,
    delivery_date: rigData.delivery_date
      ? parseISO(rigData.delivery_date)
      : null,
    special_survey_due: rigData.special_survey_due
      ? parseISO(rigData.special_survey_due)
      : null,
    end_of_last_contract: rigData.end_of_last_contract
      ? parseISO(rigData.end_of_last_contract)
      : null,
    months_in_operation_last_year: rigData.months_in_operation_last_year ?? '',
    months_in_operation_last_3_years:
      rigData.months_in_operation_last_3_years ?? '',
    design_score: rigData.design_score
      ? (rigData.design_score as DrillfloorEfficiencyEnum)
      : null,
    topside_design: rigData.topside_design
      ? (rigData.topside_design as TopsideDesignEnum)
      : null,
    tugs_no_used: rigData.tugs_no_used ?? '',
    spread_cost: rigData.spread_cost ?? '',
    day_rate: rigData.day_rate ?? '',
    quarters_capacity: rigData.quarters_capacity ?? '',
    rig_water_depth: rigData.rig_water_depth ?? '',
    variable_load: rigData.variable_load ?? '',
    hull_breadth: rigData.hull_breadth ?? '',
    hull_depth: rigData.hull_depth ?? '',
    hull_length: rigData.hull_length ?? '',
    derrick_height: rigData.derrick_height ?? '',
    derrick_capacity: rigData.derrick_capacity ?? '',
    drawworks_power: rigData.drawworks_power ?? '',
    total_cranes: rigData.total_cranes ?? '',
    crane_capacity: rigData.crane_capacity ?? '',
    total_bop_rams: rigData.total_bop_rams ?? '',
    bop_diameter_wp_max: rigData.bop_diameter_wp_max ?? '',
    bop_wp_max: rigData.bop_wp_max ?? '',
    number_of_bop_stacks: rigData.number_of_bop_stacks ?? '',
    mudpump_quantity: rigData.mudpump_quantity ?? '',
    liquid_mud: rigData.liquid_mud ?? '',
    mud_total_power: rigData.mud_total_power ?? '',
    shaleshaker_total: rigData.shaleshaker_total ?? '',
    engine_power: rigData.engine_power ?? '',
    engine_quantity: rigData.engine_quantity ?? '',
    engine_total: rigData.engine_total ?? '',
    generator_power: rigData.generator_power ?? '',
    generator_quantity: rigData.generator_quantity ?? '',
    generator_total: rigData.generator_total ?? '',
    offline_stand_building: rigData.offline_stand_building ?? false,
    auto_pipe_handling: rigData.auto_pipe_handling ?? false,
    dual_activity: rigData.dual_activity ?? false,
    drilltronic: rigData.drilltronic ?? false,
    dynamic_drilling_guide: rigData.dynamic_drilling_guide ?? false,
    process_automation_platform: rigData.process_automation_platform ?? false,
    automatic_tripping: rigData.automatic_tripping ?? false,
    closed_bus: rigData.closed_bus ?? false,
    scr: rigData.scr ?? false,
    hybrid: rigData.hybrid ?? false,
    hvac_heat_recovery: rigData.hvac_heat_recovery ?? false,
    freshwater_cooling_systems: rigData.freshwater_cooling_systems ?? false,
    seawater_cooling_systems: rigData.seawater_cooling_systems ?? false,
    operator_awareness_dashboard: rigData.operator_awareness_dashboard ?? false,
    hpu_optimization: rigData.hpu_optimization ?? false,
    optimized_heat_tracing_system:
      rigData.optimized_heat_tracing_system ?? false,
    floodlighting_optimization: rigData.floodlighting_optimization ?? false,
    vfds_on_aux_machinery: rigData.vfds_on_aux_machinery ?? false,
    drillfloor_efficiency: rigData.drillfloor_efficiency
      ? (rigData.drillfloor_efficiency as DrillfloorEfficiencyEnum)
      : null,
    equipment_load: rigData.equipment_load
      ? (rigData.equipment_load as DrillfloorEfficiencyEnum)
      : null,
    hull_concept_score: rigData.hull_concept_score ?? '',
    hull_design_eco_score: rigData.hull_design_eco_score ?? '',
    dp: rigData.dp ?? false,
    dp_class: rigData.dp_class ? (rigData.dp_class as DpClassEnum) : null,
    draft_depth: rigData.draft_depth ?? '',
    displacement: rigData.displacement ?? '',
    dual_derrick: rigData.dual_derrick ?? false,
    active_heave_drawwork: rigData.active_heave_drawwork ?? false,
    cmc_with_active_heave: rigData.cmc_with_active_heave ?? false,
    ram_system: rigData.ram_system ?? false,
    tripsaver: rigData.tripsaver ?? false,
    riser_storage_inside_hull: rigData.riser_storage_inside_hull ?? false,
    riser_on_board_outfitted: rigData.riser_on_board_outfitted ?? '',
    split_funnels_free_stern_deck:
      rigData.split_funnels_free_stern_deck ?? false,
  };
};

export const emptyFormValues: FormValues = {
  name: '',
  manager: '',
  design: '',
  build_yard: '',
  rig_status: null,
  delivery_date: null,
  special_survey_due: null,
  end_of_last_contract: null,
  months_in_operation_last_year: '',
  months_in_operation_last_3_years: '',
  design_score: null,
  topside_design: null,
  day_rate: '',
  spread_cost: '',
  tugs_no_used: '',
  quarters_capacity: '',
  rig_water_depth: '',
  variable_load: '',
  hull_breadth: '',
  hull_depth: '',
  hull_length: '',
  derrick_height: '',
  derrick_capacity: '',
  drawworks_power: '',
  total_cranes: '',
  crane_capacity: '',
  total_bop_rams: '',
  bop_diameter_wp_max: '',
  bop_wp_max: '',
  number_of_bop_stacks: '',
  mudpump_quantity: '',
  liquid_mud: '',
  mud_total_power: '',
  shaleshaker_total: '',
  engine_power: '',
  engine_quantity: '',
  engine_total: '',
  generator_power: '',
  generator_quantity: '',
  generator_total: '',
  drillfloor_efficiency: null,
  equipment_load: null,
  hull_concept_score: '',
  hull_design_eco_score: '',
  dp: false,
  dp_class: null,
  split_funnels_free_stern_deck: false,
  riser_on_board_outfitted: '',
  riser_storage_inside_hull: false,
  draft_depth: '',
  displacement: '',
  dual_derrick: false,
  active_heave_drawwork: false,
  cmc_with_active_heave: false,
  ram_system: false,
  tripsaver: false,
  offline_stand_building: false,
  auto_pipe_handling: false,
  dual_activity: false,
  drilltronic: false,
  dynamic_drilling_guide: false,
  process_automation_platform: false,
  automatic_tripping: false,
  closed_bus: false,
  scr: false,
  hybrid: false,
  hvac_heat_recovery: false,
  freshwater_cooling_systems: false,
  seawater_cooling_systems: false,
  operator_awareness_dashboard: false,
  hpu_optimization: false,
  optimized_heat_tracing_system: false,
  floodlighting_optimization: false,
  vfds_on_aux_machinery: false,
};
