import { ComponentStory, ComponentMeta } from '@storybook/react';
import Box from 'components/Box';
import CO2Chart, { CO2ChartData } from './CO2Chart';
import { ChartDataset } from 'chart.js';

export default {
  title: 'pages/WellPlan/components/CO2Chart',
  component: CO2Chart,
  argTypes: {},
} as ComponentMeta<typeof CO2Chart>;

const Template: ComponentStory<typeof CO2Chart> = (args) => (
  <Box height={500}>
    <CO2Chart {...args} />
  </Box>
);

export const Default = Template.bind({});
Default.args = {
  datasets: [
    ...([
      {
        label: 'Rig',
        data: [
          { x: '2022-07-21', y: 2.22 },
          { x: '2022-07-22', y: null },
          { x: '2022-07-23', y: null },
        ],
        maxBarThickness: 30,
        type: 'bar',
        backgroundColor: '#EAECF0',
        stack: 'PLUG_AND_ABANDON',
        skipNull: true,
        order: 2,
      } as ChartDataset<'bar', CO2ChartData[]>,
      {
        label: 'Rig',
        data: [
          { x: '2022-07-21', y: 2.22 },
          { x: '2022-07-22', y: null },
          { x: '2022-07-23', y: null },
        ],
        maxBarThickness: 30,
        type: 'bar',
        backgroundColor: '#EAECF0',
        stack: 'TOP_HOLE_SECTION',
        skipNull: true,
        order: 2,
      },
      {
        label: 'Rig',
        data: [
          { x: '2022-07-21', y: null },
          { x: '2022-07-22', y: 1.7 },
          { x: '2022-07-23', y: null },
        ],
        maxBarThickness: 30,
        type: 'bar',
        backgroundColor: '#EAECF0',
        stack: 'WAITING_ON_WEATHER',
        skipNull: true,
        order: 2,
      },
      {
        label: 'Rig',
        data: [
          { x: '2022-07-21', y: null },
          { x: '2022-07-22', y: 1.7 },
          { x: '2022-07-23', y: 2.22 },
        ],
        maxBarThickness: 30,
        type: 'bar',
        backgroundColor: '#EAECF04D',
        stack: 'SAVED_TIME',
        skipNull: true,
        order: 2,
      },
      {
        label: 'Supply vessels',
        data: [
          { x: '2022-07-21', y: 2 },
          { x: '2022-07-22', y: null },
          { x: '2022-07-23', y: null },
        ],
        maxBarThickness: 30,
        type: 'bar',
        backgroundColor: '#7471C6',
        stack: 'PLUG_AND_ABANDON',
        skipNull: true,
        order: 2,
      },
      {
        label: 'Supply vessels',
        data: [
          { x: '2022-07-21', y: 1.7 },
          { x: '2022-07-22', y: null },
          { x: '2022-07-23', y: null },
        ],
        maxBarThickness: 30,
        type: 'bar',
        backgroundColor: '#7471C6',
        stack: 'TOP_HOLE_SECTION',
        skipNull: true,
        order: 2,
      },
      {
        label: 'Supply vessels',
        data: [
          { x: '2022-07-21', y: null },
          { x: '2022-07-22', y: 0.8 },
          { x: '2022-07-23', y: null },
        ],
        maxBarThickness: 30,
        type: 'bar',
        backgroundColor: '#7471C6',
        stack: 'WAITING_ON_WEATHER',
        skipNull: true,
        order: 2,
      },
      {
        label: 'Supply vessels',
        data: [
          { x: '2022-07-21', y: null },
          { x: '2022-07-22', y: 0.8 },
          { x: '2022-07-23', y: 1.7 },
        ],
        maxBarThickness: 30,
        type: 'bar',
        backgroundColor: '#7471C64D',
        stack: 'SAVED_TIME',
        skipNull: true,
        order: 2,
      },
      {
        label: 'Helicopters',
        data: [
          { x: '2022-07-21', y: 1.5 },
          { x: '2022-07-22', y: null },
          { x: '2022-07-23', y: null },
        ],
        maxBarThickness: 30,
        type: 'bar',
        backgroundColor: '#827FCC',
        stack: 'PLUG_AND_ABANDON',
        skipNull: true,
        order: 2,
      },
      {
        label: 'Helicopters',
        data: [
          { x: '2022-07-21', y: 0.6 },
          { x: '2022-07-22', y: null },
          { x: '2022-07-23', y: null },
        ],
        maxBarThickness: 30,
        type: 'bar',
        backgroundColor: '#827FCC',
        stack: 'TOP_HOLE_SECTION',
        skipNull: true,
        order: 2,
      },
      {
        label: 'Helicopters',
        data: [
          { x: '2022-07-21', y: null },
          { x: '2022-07-22', y: 2.2 },
          { x: '2022-07-23', y: null },
        ],
        maxBarThickness: 30,
        type: 'bar',
        backgroundColor: '#827FCC',
        stack: 'WAITING_ON_WEATHER',
        skipNull: true,
        order: 2,
      },
      {
        label: 'Helicopters',
        data: [
          { x: '2022-07-21', y: null },
          { x: '2022-07-22', y: 2.2 },
          { x: '2022-07-23', y: 0.6 },
        ],
        maxBarThickness: 30,
        type: 'bar',
        backgroundColor: '#827FCC4D',
        stack: 'SAVED_TIME',
        skipNull: true,
        order: 2,
      },
      {
        label: 'External supply',
        data: [
          { x: '2022-07-21', y: 2 },
          { x: '2022-07-22', y: null },
          { x: '2022-07-23', y: null },
        ],
        maxBarThickness: 30,
        type: 'bar',
        backgroundColor: '#9D9BD7',
        stack: 'PLUG_AND_ABANDON',
        skipNull: true,
        order: 2,
      },
      {
        label: 'External supply',
        data: [
          { x: '2022-07-21', y: 0.2 },
          { x: '2022-07-22', y: null },
          { x: '2022-07-23', y: null },
        ],
        maxBarThickness: 30,
        type: 'bar',
        backgroundColor: '#9D9BD7',
        stack: 'TOP_HOLE_SECTION',
        skipNull: true,
        order: 2,
      },
      {
        label: 'External supply',
        data: [
          { x: '2022-07-21', y: null },
          { x: '2022-07-22', y: 1.33 },
          { x: '2022-07-23', y: null },
        ],
        maxBarThickness: 30,
        type: 'bar',
        backgroundColor: '#9D9BD7',
        stack: 'WAITING_ON_WEATHER',
        skipNull: true,
        order: 2,
      },
      {
        label: 'External supply',
        data: [
          { x: '2022-07-21', y: null },
          { x: '2022-07-22', y: 1.33 },
          { x: '2022-07-23', y: 0.2 },
        ],
        maxBarThickness: 30,
        type: 'bar',
        backgroundColor: '#9D9BD74D',
        stack: 'SAVED_TIME',
        skipNull: true,
        order: 2,
      },
      {
        label: 'Cement',
        data: [
          { x: '2022-07-21', y: 1.55 },
          { x: '2022-07-22', y: null },
          { x: '2022-07-23', y: null },
        ],
        maxBarThickness: 30,
        type: 'bar',
        backgroundColor: '#B9B8E2',
        stack: 'PLUG_AND_ABANDON',
        skipNull: true,
        order: 2,
      },
      {
        label: 'Cement',
        data: [
          { x: '2022-07-21', y: 0.55 },
          { x: '2022-07-22', y: null },
          { x: '2022-07-23', y: null },
        ],
        maxBarThickness: 30,
        type: 'bar',
        backgroundColor: '#B9B8E2',
        stack: 'TOP_HOLE_SECTION',
        skipNull: true,
        order: 2,
      },
      {
        label: 'Cement',
        data: [
          { x: '2022-07-21', y: null },
          { x: '2022-07-22', y: 0.5 },
          { x: '2022-07-23', y: null },
        ],
        maxBarThickness: 30,
        type: 'bar',
        backgroundColor: '#B9B8E2',
        stack: 'WAITING_ON_WEATHER',
        skipNull: true,
        order: 2,
      },
      {
        label: 'Cement',
        data: [
          { x: '2022-07-21', y: null },
          { x: '2022-07-22', y: 0.5 },
          { x: '2022-07-23', y: 0.55 },
        ],
        maxBarThickness: 30,
        type: 'bar',
        backgroundColor: '#B9B8E24D',
        stack: 'SAVED_TIME',
        skipNull: true,
        order: 2,
      },
      {
        label: 'Steel',
        data: [
          { x: '2022-07-21', y: 3.5 },
          { x: '2022-07-22', y: null },
          { x: '2022-07-23', y: null },
        ],
        maxBarThickness: 30,
        type: 'bar',
        backgroundColor: '#D5D4EE',
        stack: 'PLUG_AND_ABANDON',
        skipNull: true,
        order: 2,
      },
      {
        label: 'Steel',
        data: [
          { x: '2022-07-21', y: 0.5 },
          { x: '2022-07-22', y: null },
          { x: '2022-07-23', y: null },
        ],
        maxBarThickness: 30,
        type: 'bar',
        backgroundColor: '#D5D4EE',
        stack: 'TOP_HOLE_SECTION',
        skipNull: true,
        order: 2,
      },
      {
        label: 'Steel',
        data: [
          { x: '2022-07-21', y: null },
          { x: '2022-07-22', y: 0.35 },
          { x: '2022-07-23', y: null },
        ],
        maxBarThickness: 30,
        type: 'bar',
        backgroundColor: '#D5D4EE',
        stack: 'WAITING_ON_WEATHER',
        skipNull: true,
        order: 2,
      },
      {
        label: 'Steel',
        data: [
          { x: '2022-07-21', y: null },
          { x: '2022-07-22', y: 0.35 },
          { x: '2022-07-23', y: 0.5 },
        ],
        maxBarThickness: 30,
        type: 'bar',
        backgroundColor: '#D5D4EE4D',
        stack: 'SAVED_TIME',
        skipNull: true,
        order: 2,
      },
      {
        label: 'Emp initiative 1',
        data: [
          { x: '2022-07-21', y: 1.3 },
          { x: '2022-07-22', y: null },
          { x: '2022-07-23', y: null },
        ],
        maxBarThickness: 30,
        type: 'bar',
        backgroundColor: '#DB6B74',
        stack: 'PLUG_AND_ABANDON',
        skipNull: true,
        order: 2,
      },
      {
        label: 'Emp initiative 1',
        data: [
          { x: '2022-07-21', y: null },
          { x: '2022-07-22', y: null },
          { x: '2022-07-23', y: null },
        ],
        maxBarThickness: 30,
        type: 'bar',
        backgroundColor: '#DB6B74',
        stack: 'TOP_HOLE_SECTION',
        skipNull: true,
        order: 2,
      },
      {
        label: 'Emp initiative 1',
        data: [
          { x: '2022-07-21', y: null },
          { x: '2022-07-22', y: 1.3 },
          { x: '2022-07-23', y: null },
        ],
        maxBarThickness: 30,
        type: 'bar',
        backgroundColor: '#DB6B74',
        stack: 'WAITING_ON_WEATHER',
        skipNull: true,
        order: 2,
      },
      {
        label: 'Emp initiative 1',
        data: [
          { x: '2022-07-21', y: null },
          { x: '2022-07-22', y: 1.3 },
          { x: '2022-07-23', y: null },
        ],
        maxBarThickness: 30,
        type: 'bar',
        backgroundColor: '#DB6B744D',
        stack: 'SAVED_TIME',
        skipNull: true,
        order: 2,
      },
      {
        label: 'Emp initiative 2',
        data: [
          { x: '2022-07-21', y: null },
          { x: '2022-07-22', y: null },
          { x: '2022-07-23', y: null },
        ],
        maxBarThickness: 30,
        type: 'bar',
        backgroundColor: '#E38C93',
        stack: 'PLUG_AND_ABANDON',
        skipNull: true,
        order: 2,
      },
      {
        label: 'Emp initiative 2',
        data: [
          { x: '2022-07-21', y: 2.13 },
          { x: '2022-07-22', y: null },
          { x: '2022-07-23', y: null },
        ],
        maxBarThickness: 30,
        type: 'bar',
        backgroundColor: '#E38C93',
        stack: 'TOP_HOLE_SECTION',
        skipNull: true,
        order: 2,
      },
      {
        label: 'Emp initiative 2',
        data: [
          { x: '2022-07-21', y: null },
          { x: '2022-07-22', y: null },
          { x: '2022-07-23', y: null },
        ],
        maxBarThickness: 30,
        type: 'bar',
        backgroundColor: '#E38C93',
        stack: 'WAITING_ON_WEATHER',
        skipNull: true,
        order: 2,
      },
      {
        label: 'Emp initiative 2',
        data: [
          { x: '2022-07-21', y: null },
          { x: '2022-07-22', y: null },
          { x: '2022-07-23', y: 2.13 },
        ],
        maxBarThickness: 30,
        type: 'bar',
        backgroundColor: '#E38C934D',
        stack: 'SAVED_TIME',
        skipNull: true,
        order: 2,
      },
      {
        label: 'Emp initiative 3',
        data: [
          { x: '2022-07-21', y: null },
          { x: '2022-07-22', y: null },
          { x: '2022-07-23', y: null },
        ],
        maxBarThickness: 30,
        type: 'bar',
        backgroundColor: '#EBADB2',
        stack: 'PLUG_AND_ABANDON',
        skipNull: true,
        order: 2,
      },
      {
        label: 'Emp initiative 3',
        data: [
          { x: '2022-07-21', y: null },
          { x: '2022-07-22', y: null },
          { x: '2022-07-23', y: null },
        ],
        maxBarThickness: 30,
        type: 'bar',
        backgroundColor: '#EBADB2',
        stack: 'TOP_HOLE_SECTION',
        skipNull: true,
        order: 2,
      },
      {
        label: 'Emp initiative 3',
        data: [
          { x: '2022-07-21', y: null },
          { x: '2022-07-22', y: null },
          { x: '2022-07-23', y: null },
        ],
        maxBarThickness: 30,
        type: 'bar',
        backgroundColor: '#EBADB2',
        stack: 'WAITING_ON_WEATHER',
        skipNull: true,
        order: 2,
      },
      {
        label: 'Emp initiative 3',
        data: [
          { x: '2022-07-21', y: null },
          { x: '2022-07-22', y: null },
          { x: '2022-07-23', y: null },
        ],
        maxBarThickness: 30,
        type: 'bar',
        backgroundColor: '#EBADB24D',
        stack: 'SAVED_TIME',
        skipNull: true,
        order: 2,
      },
    ] as ChartDataset<'bar', CO2ChartData[]>[]),
    ...([
      {
        label: 'Target',
        data: [{ x: '2022-07-21', y: 12.770000000000001 }],
        type: 'line',
        borderColor: '#667085',
        borderDash: [4, 2],
        borderWidth: 2,
        order: 1,
        tension: 0.2,
      },
      {
        label: 'Target',
        data: [
          { x: '2022-07-21', y: 5.77 },
          { x: '2022-07-22', y: 6.88 },
        ],
        type: 'line',
        borderColor: '#667085',
        borderDash: [4, 2],
        borderWidth: 2,
        order: 1,
        tension: 0.2,
      },
      {
        label: 'Baseline',
        data: [{ x: '2022-07-21', y: 14.070000000000002 }],
        type: 'line',
        borderColor: '#F4CCCF',
        borderDash: [4, 2],
        borderWidth: 2,
        order: 1,
        tension: 0.2,
      },
      {
        label: 'Baseline',
        data: [
          { x: '2022-07-21', y: 7.8999999999999995 },
          { x: '2022-07-22', y: 8.18 },
        ],
        type: 'line',
        borderColor: '#F4CCCF',
        borderDash: [4, 2],
        borderWidth: 2,
        order: 1,
        tension: 0.2,
      },
    ] as ChartDataset<'line', CO2ChartData[]>[]),
  ],
};
