import {
  getGeneralValidationSchema,
  getCapacitiesValidationSchema,
  getOperationValidationSchema,
} from 'containers/UpdateSemiForm/schema';
import { DraftFormSteps } from 'consts/rigs';
import { UpdateCustomSemiRig } from 'api/schema';

export const stepValidationSchemas = {
  [DraftFormSteps.GENERAL]: getGeneralValidationSchema(false),
  [DraftFormSteps.CAPACITIES]: getCapacitiesValidationSchema(false),
  [DraftFormSteps.OPERATION]: getOperationValidationSchema(false),
};

export const stepFieldMap: {
  [key in DraftFormSteps]: (keyof UpdateCustomSemiRig)[];
} = {
  [DraftFormSteps.GENERAL]: [
    'name',
    'manager',
    'design',
    'build_yard',
    'rig_status',
    'delivery_date',
    'end_of_last_contract',
    'special_survey_due',
    'months_in_operation_last_year',
    'months_in_operation_last_3_years',
    'topside_design',
    'design_score',
    'drillfloor_efficiency',
    'day_rate',
    'spread_cost',
    'tugs_no_used',
    'move_speed',
    'draft',
  ],
  [DraftFormSteps.CAPACITIES]: [
    'active_heave_drawwork',
    'airgap',
    'anchor_standalone',
    'bop_diameter_wp_max',
    'bop_wp_max',
    'cmc_with_active_heave',
    'crane_capacity',
    'derrick_capacity',
    'derrick_height',
    'displacement',
    'dp_class',
    'dp',
    'draft_depth',
    'drawworks_power',
    'dual_derrick',
    'engine_power',
    'engine_quantity',
    'engine_total',
    'equipment_load',
    'generator_power',
    'generator_quantity',
    'generator_total',
    'hull_breadth',
    'hull_concept_score',
    'hull_depth',
    'hull_design_eco_score',
    'hull_length',
    'liquid_mud',
    'mud_total_power',
    'mudpump_quantity',
    'number_of_bop_stacks',
    'quarters_capacity',
    'ram_system',
    'rig_water_depth',
    'shaleshaker_total',
    'thruster_assist',
    'total_anchors',
    'total_bop_rams',
    'total_cranes',
    'variable_load',
    'draft',
  ],
  [DraftFormSteps.OPERATION]: [
    'offline_stand_building',
    'auto_pipe_handling',
    'dual_activity',
    'drilltronic',
    'dynamic_drilling_guide',
    'process_automation_platform',
    'automatic_tripping',
    'closed_bus',
    'scr',
    'hybrid',
    'hvac_heat_recovery',
    'freshwater_cooling_systems',
    'seawater_cooling_systems',
    'operator_awareness_dashboard',
    'hpu_optimization',
    'optimized_heat_tracing_system',
    'floodlighting_optimization',
    'vfds_on_aux_machinery',
    'tripsaver',
    'draft',
  ],
};
