import { CO2, CUBIC_METRE } from './format';

export const PROJECT_LABELS = {
  name: 'Project name',
  description: 'Project description',
  ahv_avg_fuel_consumption: 'Average AHV fuel consumption (t/d)',
  ahv_day_rate: 'AHV’s day rate (USD)',
  ahv_no_days_per_location: "Number of AHV's days per location",
  ahv_no_used: 'Number of AHVs to be used',
  co2_emission_per_m3_fuel: `Emission per ${CUBIC_METRE} fuel`,
  co2_emission_per_tonne_fuel: 'Emission per tonne fuel',
  co2_tax: `${CO2} tax (USD/t)`,
  fuel_density: `Fuel density (t/${CUBIC_METRE})`,
  fuel_total_price: 'Total fuel price (USD/t)',
  helicopter_avg_fuel_consumption: 'Average fuel consumption (t/d)',
  helicopter_fuel_price: 'Helicopter fuel price (USD/t)',
  helicopter_no_flights_per_week: 'Flights per week',
  helicopter_rate_per_trip: 'Rate per trip (USD)',
  helicopter_types: 'Type of helicopter',
  helicopter_cruise_speed: 'Cruise speed (kn)',
  marine_diesel_oil_price: 'Marine diesel oil price (USD)',
  nox_tax: 'NOX tax (USD/t)',
  psv_fuel_price: 'PSV fuel price (USD/t)',
  psv_calls_per_week: 'Calls per week',
  psv_day_rate: 'PSV’s day rate (USD)',
  psv_types: 'Type of PSV’s',
  psv_avg_fuel_transit_consumption:
    'Average PSV fuel transit consumption (t/d)',
  psv_avg_fuel_dp_consumption: 'Average PSV fuel DP consumption (t/d)',
  psv_speed: 'PSV speed (kn)',
  psv_loading_time: 'PSV loading time (d)',
  tugs_day_rate: 'Tug’s day rate (USD)',
  tugs_avg_move_fuel_consumption: 'Average Tug move fuel consumption (t/d)',
  tugs_avg_transit_fuel_consumption:
    'Average Tug transit fuel consumption (t/d)',
  tugs_move_speed: 'Tug move speed (kn)',
  tugs_transit_speed: 'Tug transit speed (kn)',
  created_at: 'Create date',
  updated_at: 'Last edited date',
};
