import {
  AirgapEnum,
  CustomSemiRigDetails,
  DpClassEnum,
  DrillfloorEfficiencyEnum,
  RigStatusEnum,
  TopsideDesignEnum,
  UpdateCustomSemiRig,
} from 'api/schema';
import { parseISO } from 'date-fns';
import { normalizeDate, normalizeNumber } from 'utils/normalize';
import { FormValues } from './useUpdateSemiForm';

export const normalizeValues = (
  values: FormValues,
  draft: boolean,
): Required<UpdateCustomSemiRig> => {
  return {
    name: values.name,
    manager: values.manager,
    design: values.design,
    build_yard: values.build_yard,
    rig_status: values.rig_status ?? '',
    drillfloor_efficiency: values.drillfloor_efficiency ?? '',
    design_score: values.design_score ?? '',
    topside_design: values.topside_design ?? '',
    equipment_load: values.equipment_load ?? '',
    day_rate: normalizeNumber(values.day_rate),
    spread_cost: normalizeNumber(values.spread_cost),
    tugs_no_used: normalizeNumber(values.tugs_no_used),
    move_speed: normalizeNumber(values.move_speed),
    dp_class: values.dp_class ?? '',
    airgap: values.airgap ?? '',
    end_of_last_contract: normalizeDate(values.end_of_last_contract),
    delivery_date: normalizeDate(values.delivery_date),
    special_survey_due: normalizeDate(values.special_survey_due),
    months_in_operation_last_year: normalizeNumber(
      values.months_in_operation_last_year,
    ),
    months_in_operation_last_3_years: normalizeNumber(
      values.months_in_operation_last_3_years,
    ),
    quarters_capacity: normalizeNumber(values.quarters_capacity),
    rig_water_depth: normalizeNumber(values.rig_water_depth),
    variable_load: normalizeNumber(values.variable_load),
    hull_breadth: normalizeNumber(values.hull_breadth),
    hull_depth: normalizeNumber(values.hull_depth),
    hull_length: normalizeNumber(values.hull_length),
    hull_concept_score: normalizeNumber(values.hull_concept_score),
    hull_design_eco_score: normalizeNumber(values.hull_design_eco_score),
    total_anchors: normalizeNumber(values.total_anchors),
    draft_depth: normalizeNumber(values.draft_depth),
    displacement: normalizeNumber(values.displacement),
    derrick_height: normalizeNumber(values.derrick_height),
    derrick_capacity: normalizeNumber(values.derrick_capacity),
    drawworks_power: normalizeNumber(values.drawworks_power),
    total_cranes: normalizeNumber(values.total_cranes),
    crane_capacity: normalizeNumber(values.crane_capacity),
    total_bop_rams: normalizeNumber(values.total_bop_rams),
    bop_diameter_wp_max: normalizeNumber(values.bop_diameter_wp_max),
    bop_wp_max: normalizeNumber(values.bop_wp_max),
    number_of_bop_stacks: normalizeNumber(values.number_of_bop_stacks),
    mudpump_quantity: normalizeNumber(values.mudpump_quantity),
    liquid_mud: normalizeNumber(values.liquid_mud),
    mud_total_power: normalizeNumber(values.mud_total_power),
    shaleshaker_total: normalizeNumber(values.shaleshaker_total),
    engine_power: normalizeNumber(values.engine_power),
    engine_quantity: normalizeNumber(values.engine_quantity),
    engine_total: normalizeNumber(values.engine_total),
    generator_power: normalizeNumber(values.generator_power),
    generator_quantity: normalizeNumber(values.generator_quantity),
    generator_total: normalizeNumber(values.generator_total),
    offline_stand_building: values.offline_stand_building,
    auto_pipe_handling: values.auto_pipe_handling,
    dual_activity: values.dual_activity,
    drilltronic: values.drilltronic,
    dynamic_drilling_guide: values.dynamic_drilling_guide,
    process_automation_platform: values.process_automation_platform,
    automatic_tripping: values.automatic_tripping,
    closed_bus: values.closed_bus,
    scr: values.scr,
    hybrid: values.hybrid,
    hvac_heat_recovery: values.hvac_heat_recovery,
    freshwater_cooling_systems: values.freshwater_cooling_systems,
    seawater_cooling_systems: values.seawater_cooling_systems,
    operator_awareness_dashboard: values.operator_awareness_dashboard,
    hpu_optimization: values.hpu_optimization,
    optimized_heat_tracing_system: values.optimized_heat_tracing_system,
    floodlighting_optimization: values.floodlighting_optimization,
    vfds_on_aux_machinery: values.vfds_on_aux_machinery,
    active_heave_drawwork: values.active_heave_drawwork,
    anchor_standalone: values.anchor_standalone,
    cmc_with_active_heave: values.cmc_with_active_heave,
    dp: values.dp,
    dual_derrick: values.dual_derrick,
    ram_system: values.ram_system,
    thruster_assist: values.thruster_assist,
    tripsaver: values.tripsaver,
    draft,
  };
};

export const getInitialValues = (
  semiRigData: CustomSemiRigDetails,
): FormValues => {
  return {
    name: semiRigData.name ?? '',
    manager: semiRigData.manager ?? '',
    design: semiRigData.design ?? '',
    build_yard: semiRigData.build_yard ?? '',
    rig_status: semiRigData.rig_status
      ? (semiRigData.rig_status as RigStatusEnum)
      : null,
    delivery_date: semiRigData.delivery_date
      ? parseISO(semiRigData.delivery_date)
      : null,
    special_survey_due: semiRigData.special_survey_due
      ? parseISO(semiRigData.special_survey_due)
      : null,
    end_of_last_contract: semiRigData.end_of_last_contract
      ? parseISO(semiRigData.end_of_last_contract)
      : null,
    months_in_operation_last_year:
      semiRigData.months_in_operation_last_year ?? '',
    months_in_operation_last_3_years:
      semiRigData.months_in_operation_last_3_years ?? '',
    design_score: semiRigData.design_score
      ? (semiRigData.design_score as DrillfloorEfficiencyEnum)
      : null,
    topside_design: semiRigData.topside_design
      ? (semiRigData.topside_design as TopsideDesignEnum)
      : null,
    day_rate: semiRigData.day_rate ?? '',
    spread_cost: semiRigData.spread_cost ?? '',
    tugs_no_used: semiRigData.tugs_no_used ?? '',
    move_speed: semiRigData.move_speed ?? '',
    quarters_capacity: semiRigData.quarters_capacity ?? '',
    rig_water_depth: semiRigData.rig_water_depth ?? '',
    variable_load: semiRigData.variable_load ?? '',
    hull_breadth: semiRigData.hull_breadth ?? '',
    hull_depth: semiRigData.hull_depth ?? '',
    hull_length: semiRigData.hull_length ?? '',
    derrick_height: semiRigData.derrick_height ?? '',
    derrick_capacity: semiRigData.derrick_capacity ?? '',
    drawworks_power: semiRigData.drawworks_power ?? '',
    total_cranes: semiRigData.total_cranes ?? '',
    crane_capacity: semiRigData.crane_capacity ?? '',
    total_bop_rams: semiRigData.total_bop_rams ?? '',
    bop_diameter_wp_max: semiRigData.bop_diameter_wp_max ?? '',
    bop_wp_max: semiRigData.bop_wp_max ?? '',
    number_of_bop_stacks: semiRigData.number_of_bop_stacks ?? '',
    mudpump_quantity: semiRigData.mudpump_quantity ?? '',
    liquid_mud: semiRigData.liquid_mud ?? '',
    mud_total_power: semiRigData.mud_total_power ?? '',
    shaleshaker_total: semiRigData.shaleshaker_total ?? '',
    engine_power: semiRigData.engine_power ?? '',
    engine_quantity: semiRigData.engine_quantity ?? '',
    engine_total: semiRigData.engine_total ?? '',
    generator_power: semiRigData.generator_power ?? '',
    generator_quantity: semiRigData.generator_quantity ?? '',
    generator_total: semiRigData.generator_total ?? '',
    offline_stand_building: semiRigData.offline_stand_building ?? false,
    auto_pipe_handling: semiRigData.auto_pipe_handling ?? false,
    dual_activity: semiRigData.dual_activity ?? false,
    drilltronic: semiRigData.drilltronic ?? false,
    dynamic_drilling_guide: semiRigData.dynamic_drilling_guide ?? false,
    process_automation_platform:
      semiRigData.process_automation_platform ?? false,
    automatic_tripping: semiRigData.automatic_tripping ?? false,
    closed_bus: semiRigData.closed_bus ?? false,
    scr: semiRigData.scr ?? false,
    hybrid: semiRigData.hybrid ?? false,
    hvac_heat_recovery: semiRigData.hvac_heat_recovery ?? false,
    freshwater_cooling_systems: semiRigData.freshwater_cooling_systems ?? false,
    seawater_cooling_systems: semiRigData.seawater_cooling_systems ?? false,
    operator_awareness_dashboard:
      semiRigData.operator_awareness_dashboard ?? false,
    hpu_optimization: semiRigData.hpu_optimization ?? false,
    optimized_heat_tracing_system:
      semiRigData.optimized_heat_tracing_system ?? false,
    floodlighting_optimization: semiRigData.floodlighting_optimization ?? false,
    vfds_on_aux_machinery: semiRigData.vfds_on_aux_machinery ?? false,
    drillfloor_efficiency: semiRigData.drillfloor_efficiency
      ? (semiRigData.drillfloor_efficiency as DrillfloorEfficiencyEnum)
      : null,
    equipment_load: semiRigData.equipment_load
      ? (semiRigData.equipment_load as DrillfloorEfficiencyEnum)
      : null,
    hull_concept_score: semiRigData.hull_concept_score ?? '',
    hull_design_eco_score: semiRigData.hull_design_eco_score ?? '',
    dp: semiRigData.dp ?? false,
    dp_class: semiRigData.dp_class
      ? (semiRigData.dp_class as DpClassEnum)
      : null,
    thruster_assist: semiRigData.thruster_assist ?? false,
    total_anchors: semiRigData.total_anchors ?? '',
    anchor_standalone: semiRigData.anchor_standalone ?? false,
    airgap: semiRigData.airgap ? (semiRigData.airgap as AirgapEnum) : null,
    draft_depth: semiRigData.draft_depth ?? '',
    displacement: semiRigData.displacement ?? '',
    dual_derrick: semiRigData.dual_derrick ?? false,
    active_heave_drawwork: semiRigData.active_heave_drawwork ?? false,
    cmc_with_active_heave: semiRigData.cmc_with_active_heave ?? false,
    ram_system: semiRigData.ram_system ?? false,
    tripsaver: semiRigData.tripsaver ?? false,
  };
};

export const emptyValues: FormValues = {
  name: '',
  manager: '',
  design: '',
  build_yard: '',
  rig_status: null,
  delivery_date: null,
  special_survey_due: null,
  end_of_last_contract: null,
  months_in_operation_last_year: '',
  months_in_operation_last_3_years: '',
  design_score: null,
  topside_design: null,
  tugs_no_used: '',
  move_speed: '',
  spread_cost: '',
  day_rate: '',
  quarters_capacity: '',
  rig_water_depth: '',
  variable_load: '',
  hull_breadth: '',
  hull_depth: '',
  hull_length: '',
  derrick_height: '',
  derrick_capacity: '',
  drawworks_power: '',
  total_cranes: '',
  crane_capacity: '',
  total_bop_rams: '',
  bop_diameter_wp_max: '',
  bop_wp_max: '',
  number_of_bop_stacks: '',
  mudpump_quantity: '',
  liquid_mud: '',
  mud_total_power: '',
  shaleshaker_total: '',
  engine_power: '',
  engine_quantity: '',
  engine_total: '',
  generator_power: '',
  generator_quantity: '',
  generator_total: '',
  offline_stand_building: false,
  auto_pipe_handling: false,
  dual_activity: false,
  drilltronic: false,
  dynamic_drilling_guide: false,
  process_automation_platform: false,
  automatic_tripping: false,
  closed_bus: false,
  scr: false,
  hybrid: false,
  hvac_heat_recovery: false,
  freshwater_cooling_systems: false,
  seawater_cooling_systems: false,
  operator_awareness_dashboard: false,
  hpu_optimization: false,
  optimized_heat_tracing_system: false,
  floodlighting_optimization: false,
  vfds_on_aux_machinery: false,
  drillfloor_efficiency: null,
  equipment_load: null,
  hull_concept_score: '',
  hull_design_eco_score: '',
  dp: false,
  dp_class: null,
  thruster_assist: false,
  total_anchors: '',
  anchor_standalone: false,
  airgap: null,
  draft_depth: '',
  displacement: '',
  dual_derrick: false,
  active_heave_drawwork: false,
  cmc_with_active_heave: false,
  ram_system: false,
  tripsaver: false,
};
