import { UpdateCustomWell } from 'api/schema';
import { UpdateDraftWellFormStep } from 'containers/UpdateDraftWellForm/useUpdateDraftWellForm';
import { WellFormStep } from 'containers/CreateWellForm/consts';

export const stepFieldMap: {
  [key in UpdateDraftWellFormStep]: (keyof Omit<UpdateCustomWell, 'draft'>)[];
} = {
  [WellFormStep.EnterGeneralInformation]: [
    'name',
    'type',
    'top_hole',
    'transport_section',
    'reservoir_section',
    'completion',
    'pna',
    'season',
    'water_depth',
    'metocean_data',
    'metocean_days_above_hs_5',
    'tvd_from_msl',
  ],
  [WellFormStep.EnterDrillingSettings]: [
    'planned_time_per_well',
    'md_from_msl',
    'expected_reservoir_pressure',
    'expected_reservoir_temperature',
    'top_hole_section_hole_size',
    'surface_casing_section_hole_size',
    'intermediate_casing_section_hole_size',
    'production_casing_section_hole_size',
    'extension_section_hole_size',
    'intermediate_casing_section_mud_type',
    'production_casing_section_mud_type',
    'extension_section_mud_type',
    'intermediate_casing_section_mud_density',
    'production_casing_section_mud_density',
    'extension_section_mud_density',
    'conductor_size',
    'conductor_weight',
    'conductor_tvd_shoe_depth',
    'conductor_md_shoe_depth',
    'surface_casing_size',
    'surface_casing_weight',
    'surface_casing_tvd_shoe_depth',
    'surface_casing_md_shoe_depth',
    'intermediate_casing_size',
    'intermediate_casing_weight',
    'intermediate_casing_tvd_shoe_depth',
    'intermediate_casing_md_shoe_depth',
    'production_casing_size',
    'production_casing_weight',
    'production_casing_tvd_shoe_depth',
    'production_casing_md_shoe_depth',
    'liner_other_size',
    'liner_other_weight',
    'liner_other_tvd_shoe_depth',
    'liner_other_md_shoe_depth',
  ],
  [WellFormStep.EnterAdditionalData]: [
    'no_well_to_be_completed',
    'planned_time_per_completion_operation',
    'subsea_xmas_tree_size',
    'xt_weight',
    'lrp_size',
    'lrp_weight',
    'xt_running_tool_size',
    'xt_running_tool_weight',
  ],
};
